/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/apple/account": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Account */
    get: operations["get_account_api_apple_account_get"]
    put?: never
    post?: never
    /** Sign Out */
    delete: operations["sign_out_api_apple_account_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Wizard */
    get: operations["get_wizard_api_apple_wizard_get"]
    put?: never
    post?: never
    /** Cancel Wizard */
    delete: operations["cancel_wizard_api_apple_wizard_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/2fa/request": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Request Code */
    post: operations["request_code_api_apple_wizard_2fa_request_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/2fa/submit": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit Code */
    post: operations["submit_code_api_apple_wizard_2fa_submit_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/import": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Import Beacons */
    post: operations["import_beacons_api_apple_wizard_import_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/resume": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Resume Wizard
     * @description Add beacons with the saved Apple session: no Apple ID, 2FA or (usually) passcode.
     */
    post: operations["resume_wizard_api_apple_wizard_resume_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/start": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start Wizard */
    post: operations["start_wizard_api_apple_wizard_start_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/unlock": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Unlock */
    post: operations["unlock_api_apple_wizard_unlock_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations["login_api_auth_login_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations["logout_api_auth_logout_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations["me_api_auth_me_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/beacons": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Beacons */
    get: operations["list_beacons_api_beacons_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/beacons/{beacon_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Beacon */
    delete: operations["delete_beacon_api_beacons__beacon_id__delete"]
    options?: never
    head?: never
    /** Update Beacon */
    patch: operations["update_beacon_api_beacons__beacon_id__patch"]
    trace?: never
  }
  "/api/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations["health_api_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/locations": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * History
     * @description Location history for all beacons (or `beacon_id`s), ordered by beacon then time.
     */
    get: operations["history_api_locations_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/locations/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Export */
    get: operations["export_api_locations_export_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/locations/visits": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Visits
     * @description When each beacon was near (lat, lon): consecutive sightings grouped into visits.
     */
    get: operations["visits_api_locations_visits_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/settings": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Settings */
    get: operations["get_settings_api_settings_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Settings */
    patch: operations["update_settings_api_settings_patch"]
    trace?: never
  }
  "/api/tracking/refresh": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refresh */
    post: operations["refresh_api_tracking_refresh_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/tracking/runs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Runs */
    get: operations["runs_api_tracking_runs_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/tracking/status": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Status */
    get: operations["status_api_tracking_status_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AccountOut */
    AccountOut: {
      /** Apple Id */
      apple_id?: string | null
      /** Connected At */
      connected_at?: string | null
      /**
       * Device Serial
       * @description How this server appears in the Apple account's device list (as a Mac).
       */
      device_serial?: string | null
      /** Display Name */
      display_name?: string | null
      /** Last Error */
      last_error?: string | null
      status: components["schemas"]["AccountStatus"]
    }
    /**
     * AccountStatus
     * @enum {string}
     */
    AccountStatus: "none" | "active" | "needs_reauth"
    /**
     * AppSettings
     * @description User-editable settings. Defaults apply until changed.
     */
    AppSettings: {
      /**
       * Poll Interval Minutes
       * @description Minutes between polls. Below 30 raises the risk of an Apple account ban.
       * @default 30
       */
      poll_interval_minutes: number
    }
    /**
     * Battery
     * @enum {string}
     */
    Battery: "full" | "medium" | "low" | "very_low"
    /**
     * BeaconKind
     * @enum {string}
     */
    BeaconKind:
      "airtag" | "iphone" | "ipad" | "mac" | "watch" | "airpods" | "other"
    /** BeaconOut */
    BeaconOut: {
      /** Apple Name */
      apple_name: string
      battery: components["schemas"]["Battery"] | null
      /** Color */
      color: string | null
      /** Emoji */
      emoji: string | null
      /** Enabled */
      enabled: boolean
      /** Id */
      id: number
      kind: components["schemas"]["BeaconKind"]
      latest: components["schemas"]["LatestLocation"] | null
      /** Location Count */
      location_count: number
      /** Model */
      model: string | null
      /**
       * Name
       * @description Display name: the user's override, else Apple's name.
       */
      name: string
      /** Paired At */
      paired_at: string | null
    }
    /** BeaconUpdate */
    BeaconUpdate: {
      /** Color */
      color?: string | null
      /** Display Name */
      display_name?: string | null
      /** Emoji */
      emoji?: string | null
      /** Enabled */
      enabled?: boolean | null
    }
    /** CandidateOut */
    CandidateOut: {
      /** Already Tracked */
      already_tracked: boolean
      /** Identifier */
      identifier: string
      kind: components["schemas"]["BeaconKind"]
      /** Model */
      model: string | null
      /** Name */
      name: string
      /** Paired At */
      paired_at: string | null
      /**
       * Personal Device
       * @description An iPhone/iPad/Mac/Watch: tracking it tracks its owner. Unticked by default.
       */
      personal_device: boolean
    }
    /** CodeRequest */
    CodeRequest: {
      /** Code */
      code: string
    }
    /** DeviceOut */
    DeviceOut: {
      /** Added At */
      added_at: string | null
      /** Id */
      id: string
      /** Model */
      model: string | null
      /** Name */
      name: string
      /** Serial */
      serial: string | null
    }
    /**
     * ExportFormat
     * @enum {string}
     */
    ExportFormat: "csv" | "geojson"
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok"
      /** Version */
      version: string
    }
    /** ImportRequest */
    ImportRequest: {
      /** Identifiers */
      identifiers: string[]
      /** Poll Interval Minutes */
      poll_interval_minutes?: number | null
    }
    /** LatestLocation */
    LatestLocation: {
      /** Accuracy M */
      accuracy_m: number | null
      /** Latitude */
      latitude: number
      /** Longitude */
      longitude: number
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string
    }
    /** LocationPoint */
    LocationPoint: {
      /** Accuracy M */
      accuracy_m: number | null
      /** Beacon Id */
      beacon_id: number
      /** Latitude */
      latitude: number
      /** Longitude */
      longitude: number
      /** @description Why this report is probably not where the beacon was. Null for good reports. */
      noise?: components["schemas"]["Noise"] | null
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string
    }
    /** LocationsResponse */
    LocationsResponse: {
      /** Points */
      points: components["schemas"]["LocationPoint"][]
      /**
       * Stays
       * @default []
       */
      stays: components["schemas"]["Stay"][]
      /** Truncated */
      truncated: boolean
    }
    /** LoginRequest */
    LoginRequest: {
      /** Password */
      password: string
    }
    /** MeResponse */
    MeResponse: {
      /** Authenticated */
      authenticated: boolean
    }
    /** MethodOut */
    MethodOut: {
      /** Id */
      id: number
      /** Kind */
      kind: string
      /** Label */
      label: string
    }
    /** MethodRequest */
    MethodRequest: {
      /** Method Id */
      method_id: number
    }
    /**
     * Noise
     * @enum {string}
     */
    Noise: "spike" | "too_fast" | "imprecise"
    /**
     * PollOutcome
     * @enum {string}
     */
    PollOutcome: "ok" | "auth_failed" | "apple_error" | "error"
    /** PollRunOut */
    PollRunOut: {
      /** Beacons Polled */
      beacons_polled: number
      /** Error */
      error: string | null
      /** Finished At */
      finished_at: string | null
      /** Id */
      id: number
      /** New Locations */
      new_locations: number
      outcome: components["schemas"]["PollOutcome"] | null
      /** Reports Seen */
      reports_seen: number
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      trigger: components["schemas"]["PollTrigger"]
    }
    /**
     * PollTrigger
     * @enum {string}
     */
    PollTrigger: "schedule" | "manual"
    /** SettingsUpdate */
    SettingsUpdate: {
      /** Poll Interval Minutes */
      poll_interval_minutes?: number | null
    }
    /** StartRequest */
    StartRequest: {
      /** Apple Id */
      apple_id: string
      /** Password */
      password: string
    }
    /**
     * Stay
     * @description A stretch where a beacon's good reports stayed in one place.
     */
    Stay: {
      /**
       * Arrived At
       * Format: date-time
       */
      arrived_at: string
      /** Beacon Id */
      beacon_id: number
      /** Latitude */
      latitude: number
      /**
       * Left At
       * Format: date-time
       */
      left_at: string
      /** Longitude */
      longitude: number
      /** Point Count */
      point_count: number
    }
    /** TrackingStatus */
    TrackingStatus: {
      account_status: components["schemas"]["AccountStatus"]
      /** Interval Minutes */
      interval_minutes: number
      last_run: components["schemas"]["PollRunOut"] | null
      /** Next Run At */
      next_run_at: string | null
      /** Refresh Available At */
      refresh_available_at: string | null
      /** Running */
      running: boolean
    }
    /** UnlockRequest */
    UnlockRequest: {
      /** Device Id */
      device_id: string
      /** Passcode */
      passcode: string
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /** Visit */
    Visit: {
      /**
       * Arrived At
       * Format: date-time
       */
      arrived_at: string
      /** Beacon Id */
      beacon_id: number
      /** Closest M */
      closest_m: number
      /**
       * Left At
       * Format: date-time
       */
      left_at: string
      /** Point Count */
      point_count: number
    }
    /** VisitsResponse */
    VisitsResponse: {
      /** Visits */
      visits: components["schemas"]["Visit"][]
    }
    /**
     * WizardStep
     * @enum {string}
     */
    WizardStep:
      | "credentials"
      | "two_factor_method"
      | "two_factor_code"
      | "device"
      | "beacons"
      | "done"
    /** WizardView */
    WizardView: {
      /** Apple Id */
      apple_id?: string | null
      /**
       * Beacons
       * @default []
       */
      beacons: components["schemas"]["CandidateOut"][]
      /** Chosen Method Id */
      chosen_method_id?: number | null
      /**
       * Devices
       * @default []
       */
      devices: components["schemas"]["DeviceOut"][]
      /** Imported Count */
      imported_count?: number | null
      /**
       * Methods
       * @default []
       */
      methods: components["schemas"]["MethodOut"][]
      /**
       * Mode
       * @description `add`: resumed from the saved session, so no Apple ID or 2FA steps.
       * @default sign_in
       * @enum {string}
       */
      mode: "sign_in" | "add"
      /** Passcode Attempts Left */
      passcode_attempts_left?: number | null
      step: components["schemas"]["WizardStep"]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_account_api_apple_account_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AccountOut"]
        }
      }
    }
  }
  sign_out_api_apple_account_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_wizard_api_apple_wizard_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
    }
  }
  cancel_wizard_api_apple_wizard_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  request_code_api_apple_wizard_2fa_request_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["MethodRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  submit_code_api_apple_wizard_2fa_submit_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  import_beacons_api_apple_wizard_import_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  resume_wizard_api_apple_wizard_resume_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
    }
  }
  start_wizard_api_apple_wizard_start_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  unlock_api_apple_wizard_unlock_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnlockRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  login_api_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  logout_api_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  me_api_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MeResponse"]
        }
      }
    }
  }
  list_beacons_api_beacons_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["BeaconOut"][]
        }
      }
    }
  }
  delete_beacon_api_beacons__beacon_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        beacon_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_beacon_api_beacons__beacon_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        beacon_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["BeaconUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["BeaconOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HealthResponse"]
        }
      }
    }
  }
  history_api_locations_get: {
    parameters: {
      query?: {
        /** @description Only these beacons. Omit for all beacons. */
        beacon_id?: number[] | null
        /** @description Default: 24 h before `to`. */
        from?: string | null
        /** @description Default: now. */
        to?: string | null
        /** @description min_lon,min_lat,max_lon,max_lat */
        bbox?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["LocationsResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  export_api_locations_export_get: {
    parameters: {
      query?: {
        format?: components["schemas"]["ExportFormat"]
        /** @description Only these beacons. Omit for all beacons. */
        beacon_id?: number[] | null
        /** @description Default: 24 h before `to`. */
        from?: string | null
        /** @description Default: now. */
        to?: string | null
        /** @description min_lon,min_lat,max_lon,max_lat */
        bbox?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  visits_api_locations_visits_get: {
    parameters: {
      query: {
        lat: number
        lon: number
        radius_m?: number
        /** @description Only these beacons. Omit for all beacons. */
        beacon_id?: number[] | null
        /** @description Default: 24 h before `to`. */
        from?: string | null
        /** @description Default: now. */
        to?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["VisitsResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_settings_api_settings_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AppSettings"]
        }
      }
    }
  }
  update_settings_api_settings_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AppSettings"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  refresh_api_tracking_refresh_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TrackingStatus"]
        }
      }
    }
  }
  runs_api_tracking_runs_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PollRunOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  status_api_tracking_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TrackingStatus"]
        }
      }
    }
  }
}
