/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/apple/account": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Account */
    get: operations["get_account_api_apple_account_get"]
    put?: never
    post?: never
    /** Sign Out */
    delete: operations["sign_out_api_apple_account_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Wizard */
    get: operations["get_wizard_api_apple_wizard_get"]
    put?: never
    post?: never
    /** Cancel Wizard */
    delete: operations["cancel_wizard_api_apple_wizard_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/2fa/request": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Request Code */
    post: operations["request_code_api_apple_wizard_2fa_request_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/2fa/submit": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit Code */
    post: operations["submit_code_api_apple_wizard_2fa_submit_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/import": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Import Beacons */
    post: operations["import_beacons_api_apple_wizard_import_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/resume": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Resume Wizard
     * @description Add beacons with the saved Apple session: no Apple ID, 2FA or (usually) passcode.
     */
    post: operations["resume_wizard_api_apple_wizard_resume_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/start": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start Wizard */
    post: operations["start_wizard_api_apple_wizard_start_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/apple/wizard/unlock": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Unlock */
    post: operations["unlock_api_apple_wizard_unlock_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login
     * @description Step one. With two-factor on, this only issues a short-lived ticket for `/auth/mfa`.
     */
    post: operations["login_api_auth_login_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations["logout_api_auth_logout_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations["me_api_auth_me_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/mfa": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Submit Mfa
     * @description Step two: a six-digit authenticator code, or one recovery code.
     */
    post: operations["submit_mfa_api_auth_mfa_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/password": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Change Password
     * @description Changing the password signs every other browser out. This one stays signed in.
     */
    post: operations["change_password_api_auth_password_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/recovery-codes": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Regenerate Recovery Codes
     * @description Replace every unused recovery code with a fresh set.
     */
    post: operations["regenerate_recovery_codes_api_auth_recovery_codes_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/security": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Security */
    get: operations["security_api_auth_security_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/sessions/revoke": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Revoke Sessions
     * @description Log out everywhere, including here.
     */
    post: operations["revoke_sessions_api_auth_sessions_revoke_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/totp/confirm": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm Totp */
    post: operations["confirm_totp_api_auth_totp_confirm_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/totp/disable": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Disable Totp */
    post: operations["disable_totp_api_auth_totp_disable_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/totp/setup": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start Totp
     * @description Mint a secret to scan. It does nothing until `/auth/totp/confirm` proves it arrived.
     */
    post: operations["start_totp_api_auth_totp_setup_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/beacons": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Beacons */
    get: operations["list_beacons_api_beacons_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/beacons/{beacon_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Beacon */
    delete: operations["delete_beacon_api_beacons__beacon_id__delete"]
    options?: never
    head?: never
    /** Update Beacon */
    patch: operations["update_beacon_api_beacons__beacon_id__patch"]
    trace?: never
  }
  "/api/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations["health_api_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/locations": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * History
     * @description Location history for all beacons (or `beacon_id`s), ordered by beacon then time.
     */
    get: operations["history_api_locations_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/locations/export": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Export */
    get: operations["export_api_locations_export_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/locations/visits": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Visits
     * @description When each beacon was near (lat, lon): consecutive sightings grouped into visits.
     */
    get: operations["visits_api_locations_visits_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/routing": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Status */
    get: operations["get_status_api_routing_get"]
    /**
     * Update
     * @description Turn predicted routes off, use the built-in engine, or connect to a Valhalla server.
     */
    put: operations["update_api_routing_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/routing/auto-download": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Auto Download */
    put: operations["auto_download_api_routing_auto_download_put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/routing/data": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Map Data
     * @description Delete every downloaded region and all road data of the built-in engine.
     */
    delete: operations["delete_map_data_api_routing_data_delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/routing/regions": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Add Region */
    post: operations["add_region_api_routing_regions_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/routing/regions/catalog": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Catalog
     * @description Every map region Geofabrik offers.
     */
    get: operations["catalog_api_routing_regions_catalog_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/routing/regions/refresh": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh Regions
     * @description Download every region again (Geofabrik updates them daily) and rebuild the road data.
     */
    post: operations["refresh_regions_api_routing_regions_refresh_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/routing/regions/{region_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove Region */
    delete: operations["remove_region_api_routing_regions__region_id__delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/routing/routes": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Routes
     * @description History's predicted routes, trip by trip. Trips not matched yet are matched in the background:
     *     `progress` says how far along that is, and where to ask for the rest.
     */
    get: operations["routes_api_routing_routes_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/routing/routes/jobs/{job_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Job Routes
     * @description A job's trips matched since the first `after`. Gone (404) once nobody asked for a while.
     */
    get: operations["job_routes_api_routing_routes_jobs__job_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/settings": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Settings */
    get: operations["get_settings_api_settings_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Settings */
    patch: operations["update_settings_api_settings_patch"]
    trace?: never
  }
  "/api/tracking/refresh": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refresh */
    post: operations["refresh_api_tracking_refresh_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/tracking/runs": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Runs */
    get: operations["runs_api_tracking_runs_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/tracking/status": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Status */
    get: operations["status_api_tracking_status_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AccountOut */
    AccountOut: {
      /** Apple Id */
      apple_id?: string | null
      /** Connected At */
      connected_at?: string | null
      /**
       * Device Serial
       * @description How this server appears in the Apple account's device list (as a Mac).
       */
      device_serial?: string | null
      /** Display Name */
      display_name?: string | null
      /** Last Error */
      last_error?: string | null
      status: components["schemas"]["AccountStatus"]
    }
    /**
     * AccountStatus
     * @enum {string}
     */
    AccountStatus: "none" | "active" | "needs_reauth"
    /**
     * AppSettings
     * @description User-editable settings. Defaults apply until changed.
     */
    AppSettings: {
      /**
       * Api Docs
       * @description Serve the API documentation at /api/docs, to the signed-in admin only.
       * @default false
       */
      api_docs: boolean
      /**
       * Poll Interval Minutes
       * @description Minutes between checks: 30 minutes to 7 days.
       * @default 30
       */
      poll_interval_minutes: number
    }
    /** AutoDownloadUpdate */
    AutoDownloadUpdate: {
      /** Enabled */
      enabled: boolean
    }
    /**
     * Battery
     * @enum {string}
     */
    Battery: "full" | "medium" | "low" | "very_low"
    /**
     * BeaconKind
     * @enum {string}
     */
    BeaconKind:
      "airtag" | "iphone" | "ipad" | "mac" | "watch" | "airpods" | "other"
    /** BeaconOut */
    BeaconOut: {
      /** Apple Name */
      apple_name: string
      battery: components["schemas"]["Battery"] | null
      /** Color */
      color: string | null
      /** Emoji */
      emoji: string | null
      /** Enabled */
      enabled: boolean
      /** Id */
      id: number
      kind: components["schemas"]["BeaconKind"]
      latest: components["schemas"]["LatestLocation"] | null
      /** Location Count */
      location_count: number
      /** Model */
      model: string | null
      /**
       * Name
       * @description Display name: the user's override, else Apple's name.
       */
      name: string
      /** Paired At */
      paired_at: string | null
      /**
       * Vehicle
       * @description Lives in a vehicle: predicted routes treat it as a car.
       */
      vehicle: boolean
    }
    /** BeaconUpdate */
    BeaconUpdate: {
      /** Color */
      color?: string | null
      /** Display Name */
      display_name?: string | null
      /** Emoji */
      emoji?: string | null
      /** Enabled */
      enabled?: boolean | null
      /** Vehicle */
      vehicle?: boolean | null
    }
    /** BuiltinOut */
    BuiltinOut: {
      /** Auto Download */
      auto_download: boolean
      /** Built At */
      built_at: string | null
      /**
       * Detail
       * @description What it is doing, for people.
       */
      detail: string | null
      /** Disk Bytes */
      disk_bytes: number
      /** Error */
      error: string | null
      phase: components["schemas"]["Phase"]
      /** Progress */
      progress: number | null
      /** Regions */
      regions: components["schemas"]["RegionOut"][]
      /** Serving */
      serving: boolean
    }
    /** CandidateOut */
    CandidateOut: {
      /** Already Tracked */
      already_tracked: boolean
      /** Identifier */
      identifier: string
      kind: components["schemas"]["BeaconKind"]
      /** Model */
      model: string | null
      /** Name */
      name: string
      /** Paired At */
      paired_at: string | null
      /**
       * Personal Device
       * @description An iPhone/iPad/Mac/Watch: tracking it tracks its owner. Unticked by default.
       */
      personal_device: boolean
    }
    /** CatalogRegion */
    CatalogRegion: {
      /** Id */
      id: string
      /** Name */
      name: string
      /**
       * Parent
       * @description The name of the region it is part of.
       */
      parent: string | null
    }
    /** CodeRequest */
    CodeRequest: {
      /** Code */
      code: string
    }
    /**
     * Costing
     * @enum {string}
     */
    Costing: "auto" | "pedestrian"
    /** DeviceOut */
    DeviceOut: {
      /** Added At */
      added_at: string | null
      /** Id */
      id: string
      /** Model */
      model: string | null
      /** Name */
      name: string
      /** Serial */
      serial: string | null
    }
    /**
     * ExportFormat
     * @enum {string}
     */
    ExportFormat: "csv" | "geojson"
    /** ExternalOut */
    ExternalOut: {
      /** Error */
      error: string | null
      /** Reachable */
      reachable: boolean
      /** Url */
      url: string
      /** Version */
      version: string | null
    }
    /**
     * Fallback
     * @description Why a trip has no predicted route; it is drawn as reported instead.
     * @enum {string}
     */
    Fallback: "no_roads" | "error"
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok"
      /** Version */
      version?: string | null
    }
    /** ImportRequest */
    ImportRequest: {
      /** Identifiers */
      identifiers: string[]
      /** Poll Interval Minutes */
      poll_interval_minutes?: number | null
    }
    /** LatestLocation */
    LatestLocation: {
      /** Accuracy M */
      accuracy_m: number | null
      /** Latitude */
      latitude: number
      /** Longitude */
      longitude: number
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string
    }
    /** LocationPoint */
    LocationPoint: {
      /** Accuracy M */
      accuracy_m: number | null
      /** Beacon Id */
      beacon_id: number
      /** Latitude */
      latitude: number
      /** Longitude */
      longitude: number
      /** @description Why this report is probably not where the beacon was. Null for good reports. */
      noise?: components["schemas"]["Noise"] | null
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string
    }
    /** LocationsResponse */
    LocationsResponse: {
      /** Points */
      points: components["schemas"]["LocationPoint"][]
      /**
       * Stays
       * @default []
       */
      stays: components["schemas"]["Stay"][]
      /** Truncated */
      truncated: boolean
    }
    /** LoginAttemptOut */
    LoginAttemptOut: {
      /**
       * At
       * Format: date-time
       */
      at: string
      /** Client Ip */
      client_ip: string
      outcome: components["schemas"]["LoginOutcome"]
      /** User Agent */
      user_agent: string | null
    }
    /**
     * LoginOutcome
     * @enum {string}
     */
    LoginOutcome:
      | "success"
      | "wrong_password"
      | "wrong_code"
      | "recovery_used"
      | "rate_limited"
    /** LoginRequest */
    LoginRequest: {
      /** Password */
      password: string
    }
    /** LoginResponse */
    LoginResponse: {
      /**
       * Mfa Required
       * @description Post the authenticator code to /auth/mfa to finish.
       */
      mfa_required: boolean
    }
    /** MeResponse */
    MeResponse: {
      /** Authenticated */
      authenticated: boolean
    }
    /** MethodOut */
    MethodOut: {
      /** Id */
      id: number
      /** Kind */
      kind: string
      /** Label */
      label: string
    }
    /** MethodRequest */
    MethodRequest: {
      /** Method Id */
      method_id: number
    }
    /** MfaRequest */
    MfaRequest: {
      /**
       * Code
       * @description A six-digit authenticator code, or one recovery code.
       */
      code: string
    }
    /**
     * Noise
     * @enum {string}
     */
    Noise: "spike" | "too_fast" | "imprecise"
    /** PasswordChange */
    PasswordChange: {
      /** Current Password */
      current_password: string
      /** New Password */
      new_password: string
    }
    /**
     * PasswordConfirm
     * @description Re-entering the password guards changes to the second factor.
     */
    PasswordConfirm: {
      /** Password */
      password: string
    }
    /**
     * Phase
     * @enum {string}
     */
    Phase: "idle" | "downloading" | "building" | "starting"
    /**
     * PollOutcome
     * @enum {string}
     */
    PollOutcome: "ok" | "auth_failed" | "apple_error" | "error"
    /** PollRunOut */
    PollRunOut: {
      /** Beacons Polled */
      beacons_polled: number
      /** Error */
      error: string | null
      /** Finished At */
      finished_at: string | null
      /** Id */
      id: number
      /** New Locations */
      new_locations: number
      outcome: components["schemas"]["PollOutcome"] | null
      /** Reports Seen */
      reports_seen: number
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      trigger: components["schemas"]["PollTrigger"]
    }
    /**
     * PollTrigger
     * @enum {string}
     */
    PollTrigger: "schedule" | "manual"
    /** RecoveryCodes */
    RecoveryCodes: {
      /**
       * Codes
       * @description Shown once. They cannot be retrieved again.
       */
      codes: string[]
    }
    /** RegionAdd */
    RegionAdd: {
      /** Id */
      id: string
    }
    /** RegionOut */
    RegionOut: {
      /**
       * Auto
       * @description Added automatically, because history was there.
       */
      auto: boolean
      /** Error */
      error: string | null
      /** Id */
      id: string
      /**
       * In Use
       * @description Part of the road data being served.
       */
      in_use: boolean
      /** Name */
      name: string
      /**
       * Progress
       * @description 0..1 while downloading.
       */
      progress: number | null
      /** Size Bytes */
      size_bytes: number | null
      status: components["schemas"]["RegionStatus"]
    }
    /**
     * RegionStatus
     * @enum {string}
     */
    RegionStatus:
      "queued" | "downloading" | "downloaded" | "failed" | "too_large"
    /**
     * RegionSuggestion
     * @description A map region history needs but the built-in engine does not have.
     */
    RegionSuggestion: {
      /** Beacons */
      beacons: string[]
      /** Id */
      id: string
      /** Name */
      name: string
    }
    /** RoutedReport */
    RoutedReport: {
      /** Latitude */
      latitude: number
      /** Longitude */
      longitude: number
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string
      /**
       * Off Route
       * @description Not on the predicted route: probably a finder on a nearby road. Its position here is where the route was at that time.
       */
      off_route: boolean
      /**
       * Offset M
       * @description Metres along the trip's route.
       */
      offset_m: number
    }
    /** RoutesProgress */
    RoutesProgress: {
      /**
       * Done
       * @description 0..1: how much of the matching is done, counted in reports.
       */
      done: number
      /**
       * Job
       * @description Ask `/routing/routes/jobs/{job}` for the trips matched since.
       */
      job: string
      /**
       * Received
       * @description This job's trips sent so far: the next ask's `after`.
       */
      received: number
      /** Trips Left */
      trips_left: number
    }
    /** RoutesResponse */
    RoutesResponse: {
      /** Message */
      message: string | null
      /** @description Trips are still being matched: how far along it is, and where to ask next. */
      progress: components["schemas"]["RoutesProgress"] | null
      state: components["schemas"]["RoutesState"]
      /** Trips */
      trips: components["schemas"]["TripRoute"][]
    }
    /**
     * RoutesState
     * @enum {string}
     */
    RoutesState: "ok" | "off" | "unavailable"
    /**
     * RoutingMode
     * @enum {string}
     */
    RoutingMode: "off" | "builtin" | "external"
    /** RoutingStatus */
    RoutingStatus: {
      builtin: components["schemas"]["BuiltinOut"] | null
      /** Catalog Available */
      catalog_available: boolean
      /**
       * Configured By Env
       * @description ROUTING_URL is set: the server's operator chose it, Settings cannot change it.
       */
      configured_by_env: boolean
      external: components["schemas"]["ExternalOut"] | null
      /**
       * Message
       * @description What is missing, when not ready. For people.
       */
      message: string | null
      /** Missing Regions */
      missing_regions: components["schemas"]["RegionSuggestion"][]
      mode: components["schemas"]["RoutingMode"]
      /**
       * Ready
       * @description Predicted routes can be shown right now.
       */
      ready: boolean
    }
    /** RoutingUpdate */
    RoutingUpdate: {
      mode: components["schemas"]["RoutingMode"]
      /** Url */
      url?: string | null
    }
    /** SecurityStatus */
    SecurityStatus: {
      /**
       * Password Changed At
       * Format: date-time
       */
      password_changed_at: string
      /** Recent Attempts */
      recent_attempts: components["schemas"]["LoginAttemptOut"][]
      /** Recovery Codes Remaining */
      recovery_codes_remaining: number
      /** Totp Enabled */
      totp_enabled: boolean
    }
    /** SettingsUpdate */
    SettingsUpdate: {
      /** Api Docs */
      api_docs?: boolean | null
      /** Poll Interval Minutes */
      poll_interval_minutes?: number | null
    }
    /** StartRequest */
    StartRequest: {
      /** Apple Id */
      apple_id: string
      /** Password */
      password: string
    }
    /**
     * Stay
     * @description A stretch where a beacon's good reports stayed in one place.
     */
    Stay: {
      /**
       * Arrived At
       * Format: date-time
       */
      arrived_at: string
      /** Beacon Id */
      beacon_id: number
      /** Latitude */
      latitude: number
      /**
       * Left At
       * Format: date-time
       */
      left_at: string
      /** Longitude */
      longitude: number
      /** Point Count */
      point_count: number
    }
    /** TotpSetup */
    TotpSetup: {
      /**
       * Qr Data Uri
       * @description The same URI as an SVG QR code, for an <img src>.
       */
      qr_data_uri: string
      /**
       * Secret
       * @description Type this into the app if the QR code cannot be scanned.
       */
      secret: string
      /** Uri */
      uri: string
    }
    /** TrackingStatus */
    TrackingStatus: {
      account_status: components["schemas"]["AccountStatus"]
      /** Interval Minutes */
      interval_minutes: number
      last_run: components["schemas"]["PollRunOut"] | null
      /** Next Run At */
      next_run_at: string | null
      /** Refresh Available At */
      refresh_available_at: string | null
      /** Running */
      running: boolean
    }
    /** TripRoute */
    TripRoute: {
      /** Beacon Id */
      beacon_id: number
      /**
       * Broken After
       * @description Indices into `reports`: the way from that report to the next is not known.
       */
      broken_after: number[]
      costing: components["schemas"]["Costing"]
      /** @description Why there is no predicted route; draw the trip as reported instead. */
      fallback: components["schemas"]["Fallback"] | null
      /**
       * Geometry
       * @description [longitude, latitude] pairs.
       */
      geometry: [number, number][]
      /** Reports */
      reports: components["schemas"]["RoutedReport"][]
    }
    /** UnlockRequest */
    UnlockRequest: {
      /** Device Id */
      device_id: string
      /** Passcode */
      passcode: string
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /** Visit */
    Visit: {
      /**
       * Arrived At
       * Format: date-time
       */
      arrived_at: string
      /** Beacon Id */
      beacon_id: number
      /** Closest M */
      closest_m: number
      /**
       * Left At
       * Format: date-time
       */
      left_at: string
      /** Point Count */
      point_count: number
    }
    /** VisitsResponse */
    VisitsResponse: {
      /** Visits */
      visits: components["schemas"]["Visit"][]
    }
    /**
     * WizardStep
     * @enum {string}
     */
    WizardStep:
      | "credentials"
      | "two_factor_method"
      | "two_factor_code"
      | "device"
      | "beacons"
      | "done"
    /** WizardView */
    WizardView: {
      /** Apple Id */
      apple_id?: string | null
      /**
       * Beacons
       * @default []
       */
      beacons: components["schemas"]["CandidateOut"][]
      /** Chosen Method Id */
      chosen_method_id?: number | null
      /**
       * Devices
       * @default []
       */
      devices: components["schemas"]["DeviceOut"][]
      /** Imported Count */
      imported_count?: number | null
      /**
       * Methods
       * @default []
       */
      methods: components["schemas"]["MethodOut"][]
      /**
       * Mode
       * @description `add`: resumed from the saved session, so no Apple ID or 2FA steps.
       * @default sign_in
       * @enum {string}
       */
      mode: "sign_in" | "add"
      /** Passcode Attempts Left */
      passcode_attempts_left?: number | null
      step: components["schemas"]["WizardStep"]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_account_api_apple_account_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AccountOut"]
        }
      }
    }
  }
  sign_out_api_apple_account_delete: {
    parameters: {
      query?: {
        /** @description Also delete every beacon and its whole history. */
        purge?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_wizard_api_apple_wizard_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
    }
  }
  cancel_wizard_api_apple_wizard_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  request_code_api_apple_wizard_2fa_request_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["MethodRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  submit_code_api_apple_wizard_2fa_submit_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  import_beacons_api_apple_wizard_import_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  resume_wizard_api_apple_wizard_resume_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
    }
  }
  start_wizard_api_apple_wizard_start_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  unlock_api_apple_wizard_unlock_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnlockRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WizardView"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  login_api_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["LoginResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  logout_api_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  me_api_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MeResponse"]
        }
      }
    }
  }
  submit_mfa_api_auth_mfa_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["MfaRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  change_password_api_auth_password_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordChange"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  regenerate_recovery_codes_api_auth_recovery_codes_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordConfirm"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RecoveryCodes"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  security_api_auth_security_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SecurityStatus"]
        }
      }
    }
  }
  revoke_sessions_api_auth_sessions_revoke_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  confirm_totp_api_auth_totp_confirm_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["MfaRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RecoveryCodes"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  disable_totp_api_auth_totp_disable_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordConfirm"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  start_totp_api_auth_totp_setup_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TotpSetup"]
        }
      }
    }
  }
  list_beacons_api_beacons_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["BeaconOut"][]
        }
      }
    }
  }
  delete_beacon_api_beacons__beacon_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        beacon_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_beacon_api_beacons__beacon_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        beacon_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["BeaconUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["BeaconOut"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HealthResponse"]
        }
      }
    }
  }
  history_api_locations_get: {
    parameters: {
      query?: {
        /** @description Only these beacons. Omit for all beacons. */
        beacon_id?: number[] | null
        /** @description Default: 24 h before `to`. */
        from?: string | null
        /** @description Default: now. */
        to?: string | null
        /** @description min_lon,min_lat,max_lon,max_lat */
        bbox?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["LocationsResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  export_api_locations_export_get: {
    parameters: {
      query?: {
        format?: components["schemas"]["ExportFormat"]
        /** @description Only these beacons. Omit for all beacons. */
        beacon_id?: number[] | null
        /** @description Default: 24 h before `to`. */
        from?: string | null
        /** @description Default: now. */
        to?: string | null
        /** @description min_lon,min_lat,max_lon,max_lat */
        bbox?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  visits_api_locations_visits_get: {
    parameters: {
      query: {
        lat: number
        lon: number
        radius_m?: number
        /** @description Only these beacons. Omit for all beacons. */
        beacon_id?: number[] | null
        /** @description Default: 24 h before `to`. */
        from?: string | null
        /** @description Default: now. */
        to?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["VisitsResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_status_api_routing_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RoutingStatus"]
        }
      }
    }
  }
  update_api_routing_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RoutingUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RoutingStatus"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  auto_download_api_routing_auto_download_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["AutoDownloadUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RoutingStatus"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  delete_map_data_api_routing_data_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RoutingStatus"]
        }
      }
    }
  }
  add_region_api_routing_regions_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegionAdd"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RoutingStatus"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  catalog_api_routing_regions_catalog_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CatalogRegion"][]
        }
      }
    }
  }
  refresh_regions_api_routing_regions_refresh_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RoutingStatus"]
        }
      }
    }
  }
  remove_region_api_routing_regions__region_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        region_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RoutingStatus"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  routes_api_routing_routes_get: {
    parameters: {
      query?: {
        /** @description Omit for all beacons. */
        beacon_id?: number[] | null
        from?: string | null
        to?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RoutesResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  job_routes_api_routing_routes_jobs__job_id__get: {
    parameters: {
      query?: {
        /** @description How many of its trips were received. */
        after?: number
      }
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["RoutesResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_settings_api_settings_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AppSettings"]
        }
      }
    }
  }
  update_settings_api_settings_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AppSettings"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  refresh_api_tracking_refresh_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TrackingStatus"]
        }
      }
    }
  }
  runs_api_tracking_runs_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PollRunOut"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  status_api_tracking_status_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["TrackingStatus"]
        }
      }
    }
  }
}
